packages:
  - .
  - projects/wkly-datetime-picker.core
  - projects/wkly-datetime-picker.adapters
  - projects/wkly-datetime-picker
  - projects/wkly-datetime-picker.showcase
  - projects/wkly-datetime-picker.runtime
  - projects/wkly-datetime-picker.runtime.11
  - projects/wkly-datetime-picker.runtime.13
  - projects/wkly-datetime-picker.13
  - projects/wkly-datetime-picker.runtime.14
  - projects/wkly-datetime-picker.14
  - projects/wkly-datetime-picker.runtime.15
  - projects/wkly-datetime-picker.15
  - projects/wkly-datetime-picker.runtime.18
  - projects/wkly-datetime-picker.18
  - projects/wkly-datetime-picker.runtime.19
  - projects/wkly-datetime-picker.19
  - projects/wkly-datetime-picker.runtime.20
  - projects/wkly-datetime-picker.20
  - projects/wkly-datetime-picker.runtime.21
  - projects/wkly-datetime-picker.21
  - projects/wkly-datetime-picker.runtime.22
  - projects/wkly-datetime-picker.22
